apiVersion: apps/v1
kind: Deployment
metadata:
  name: division
spec:
  replicas: 1
  selector:
    matchLabels:
      app: division
  template:
    metadata:
      labels:
        app: division
    spec:
      containers:
      - name: division
        image: kilabs/cloud-engineer-challenge-calculator:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: division
spec:
  selector:
    app: division
  ports:
  - port: 80
    targetPort: 3001
  