apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplication
  template:
    metadata:
      labels:
        app: multiplication
    spec:
      containers:
      - name: multiplication
        image: kilabs/cloud-engineer-challenge-calculator:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: multiplication
spec:
  selector:
    app: multiplication
  ports:
  - port: 80
    targetPort: 3005
  