apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addition
  template:
    metadata:
      labels:
        app: addition
    spec:
      containers:
      - name: addition
        image: kilabs/cloud-engineer-challenge-calculator:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: addition
spec:
  selector:
    app: addition
  ports:
  - port: 80
    targetPort: 3000
  